# Generated by Django 5.1.4 on 2024-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField(max_length=10)),
                ('sub', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
